import type { DashboardData, StatisticsData, User, WordDetail } from './types'

export const mockUser: User = {
  id: 10001,
  username: 'demo',
  nickname: '小词同学',
  email: 'demo@example.com',
  avatarText: '词',
  continuousDays: 12,
  settings: {
    dailyNewWords: 20,
    dailyReviewLimit: 80,
    preferredLevel: 'BOTH',
    reminderTime: '20:30',
    soundEnabled: true,
  },
}

export const mockWords: WordDetail[] = [
  {
    id: 1,
    word: 'contemplate',
    phonetic: '/ˈkɒntəmpleɪt/',
    level: ['CET6'],
    briefDefinition: '沉思；仔细考虑',
    mastery: 'LEARNING',
    senses: [
      { partOfSpeech: 'v.', definitionCn: '深思，仔细考虑', definitionEn: 'to think deeply about something' },
      { partOfSpeech: 'v.', definitionCn: '考虑接受或采取', definitionEn: 'to consider doing or accepting something' },
    ],
    examples: [
      { sentence: 'She contemplated the problem from every angle.', translation: '她从各个角度仔细考虑了这个问题。' },
      { sentence: 'He is contemplating a career change.', translation: '他正在考虑转行。' },
    ],
    collocations: ['contemplate doing sth.', 'contemplate the future', 'seriously contemplate'],
    usageNote: '后接动名词，不接不定式：contemplate doing，而不是 contemplate to do。',
    memoryTip: 'con-（共同）+ temple（庙宇）：像在安静的庙宇里沉思。',
    source: 'CET-6 licensed word list / editorial annotation',
  },
  {
    id: 2,
    word: 'versatile',
    phonetic: '/ˈvɜːsətaɪl/',
    level: ['CET6'],
    briefDefinition: '多才多艺的；用途广泛的',
    mastery: 'NEW',
    senses: [{ partOfSpeech: 'adj.', definitionCn: '多才多艺的；多用途的', definitionEn: 'able to adapt or be used for many purposes' }],
    examples: [{ sentence: 'This versatile tool works in several different ways.', translation: '这件多用途工具有好几种用法。' }],
    collocations: ['highly versatile', 'versatile performer', 'versatile material'],
    usageNote: '既可以形容人能力多样，也可以形容工具或材料用途广泛。',
    memoryTip: 'verse 有“转”的感觉，能够灵活转向多种用途。',
    source: 'CET-6 licensed word list / editorial annotation',
  },
  {
    id: 3,
    word: 'deteriorate',
    phonetic: '/dɪˈtɪəriəreɪt/',
    level: ['CET6'],
    briefDefinition: '恶化；变坏',
    mastery: 'FAMILIAR',
    senses: [{ partOfSpeech: 'v.', definitionCn: '恶化，质量下降', definitionEn: 'to become worse in quality or condition' }],
    examples: [{ sentence: 'The weather began to deteriorate rapidly.', translation: '天气开始迅速恶化。' }],
    collocations: ['deteriorate rapidly', 'condition deteriorates', 'relations deteriorate'],
    usageNote: '常作不及物动词，主语通常是情况、健康、关系或质量。',
    memoryTip: '联想“低（de）到更糟的状态”。',
    source: 'CET-6 licensed word list / editorial annotation',
  },
  {
    id: 4,
    word: 'allocate',
    phonetic: '/ˈæləkeɪt/',
    level: ['CET4', 'CET6'],
    briefDefinition: '分配；拨给',
    mastery: 'MASTERED',
    senses: [{ partOfSpeech: 'v.', definitionCn: '分配资源、时间或资金', definitionEn: 'to distribute something for a particular purpose' }],
    examples: [{ sentence: 'The team allocated more time to testing.', translation: '团队为测试分配了更多时间。' }],
    collocations: ['allocate resources', 'allocate funds to', 'allocate time for'],
    usageNote: '常用结构：allocate sth. to sb./sth. 或 allocate sth. for sth.。',
    memoryTip: 'al + locate：把资源“定位”到某个地方。',
    source: 'CET-4/6 licensed word list / editorial annotation',
  },
  {
    id: 5,
    word: 'ambiguous',
    phonetic: '/æmˈbɪɡjuəs/',
    level: ['CET6'],
    briefDefinition: '含糊不清的；有歧义的',
    mastery: 'LEARNING',
    senses: [{ partOfSpeech: 'adj.', definitionCn: '有多种解释的，不明确的', definitionEn: 'open to more than one interpretation' }],
    examples: [{ sentence: 'The wording of the question is ambiguous.', translation: '这个问题的措辞有歧义。' }],
    collocations: ['ambiguous statement', 'remain ambiguous', 'deliberately ambiguous'],
    usageNote: '强调语言或含义可以有多种解释；vague 更侧重信息不具体。',
    memoryTip: 'ambi- 表示“两边”，两边都说得通，所以有歧义。',
    source: 'CET-6 licensed word list / editorial annotation',
  },
  {
    id: 6,
    word: 'coherent',
    phonetic: '/kəʊˈhɪərənt/',
    level: ['CET6'],
    briefDefinition: '连贯的；条理清楚的',
    mastery: 'NEW',
    senses: [{ partOfSpeech: 'adj.', definitionCn: '逻辑连贯、容易理解的', definitionEn: 'logical, consistent, and easy to understand' }],
    examples: [{ sentence: 'She presented a clear and coherent argument.', translation: '她提出了清晰而连贯的论点。' }],
    collocations: ['coherent argument', 'coherent strategy', 'remain coherent'],
    usageNote: '常形容论述、计划、政策或说话方式。',
    memoryTip: 'co-（一起）+ here（黏住）：观点都黏在一起，很连贯。',
    source: 'CET-6 licensed word list / editorial annotation',
  },
  {
    id: 7,
    word: 'inevitable',
    phonetic: '/ɪnˈevɪtəbl/',
    level: ['CET4', 'CET6'],
    briefDefinition: '不可避免的',
    mastery: 'FAMILIAR',
    senses: [{ partOfSpeech: 'adj.', definitionCn: '必然发生、无法避免的', definitionEn: 'certain to happen and impossible to avoid' }],
    examples: [{ sentence: 'Some degree of change is inevitable.', translation: '某种程度的变化是不可避免的。' }],
    collocations: ['inevitable result', 'seem inevitable', 'almost inevitable'],
    usageNote: '常用于客观趋势或结果，名词形式为 inevitability。',
    memoryTip: 'in-（不）+ evitable（可避免的）。',
    source: 'CET-4/6 licensed word list / editorial annotation',
  },
  {
    id: 8,
    word: 'substantial',
    phonetic: '/səbˈstænʃl/',
    level: ['CET4', 'CET6'],
    briefDefinition: '大量的；重大的；实质的',
    mastery: 'LEARNING',
    senses: [{ partOfSpeech: 'adj.', definitionCn: '数量或程度很大的', definitionEn: 'large in amount, value, or importance' }],
    examples: [{ sentence: 'The project requires substantial investment.', translation: '这个项目需要大量投资。' }],
    collocations: ['substantial amount', 'substantial evidence', 'substantial improvement'],
    usageNote: '比 big 正式，常搭配 amount、evidence、investment、change。',
    memoryTip: 'substance 是“实质”，有实质分量就是 substantial。',
    source: 'CET-4/6 licensed word list / editorial annotation',
  },
]

export const mockDashboard: DashboardData = {
  greeting: '把今天的 20 个新词，变成明天的熟词。',
  learnedToday: 12,
  newWordTarget: 20,
  reviewedToday: 28,
  reviewDue: 16,
  masteredTotal: 486,
  continuousDays: 12,
  weeklyActivity: [
    { date: '07-07', label: '一', count: 18, target: 20 },
    { date: '07-08', label: '二', count: 20, target: 20 },
    { date: '07-09', label: '三', count: 14, target: 20 },
    { date: '07-10', label: '四', count: 22, target: 20 },
    { date: '07-11', label: '五', count: 20, target: 20 },
    { date: '07-12', label: '六', count: 16, target: 20 },
    { date: '07-13', label: '日', count: 12, target: 20 },
  ],
  difficultWords: [mockWords[0]!, mockWords[4]!, mockWords[7]!],
}

export const mockStatistics: StatisticsData = {
  range: '7D',
  totalLearned: 142,
  totalMastered: 486,
  reviewAccuracy: 86,
  totalMinutes: 214,
  daily: [
    { date: '07-07', label: '周一', learned: 18, reviewed: 42 },
    { date: '07-08', label: '周二', learned: 20, reviewed: 35 },
    { date: '07-09', label: '周三', learned: 14, reviewed: 30 },
    { date: '07-10', label: '周四', learned: 22, reviewed: 48 },
    { date: '07-11', label: '周五', learned: 20, reviewed: 52 },
    { date: '07-12', label: '周六', learned: 16, reviewed: 36 },
    { date: '07-13', label: '今天', learned: 12, reviewed: 28 },
  ],
  masteryDistribution: [
    { label: '已掌握', value: 486, color: '#2f7668' },
    { label: '熟悉', value: 238, color: '#7e9f78' },
    { label: '学习中', value: 164, color: '#e9a23b' },
    { label: '新词', value: 92, color: '#e8ded0' },
  ],
  recentAchievements: [
    { title: '连续学习 12 天', description: '学习节奏已经开始稳定下来', date: '今天' },
    { title: '本周复习达人', description: '本周累计完成 271 次复习', date: '昨天' },
    { title: '掌握 400 词', description: '四级六级差集词库完成 21%', date: '07-09' },
  ],
}
